'use client';
import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { ArrowUpRight, MessageCircle, RefreshCw, ShoppingBag } from 'lucide-react';
import './agent-work.css';

type Lead = { url: string; title: string; platform?: string; asking_price_cents: number | null; usable_capacity_gb?: number; notes: string[] };
type Watch = { id: string; query: string; platform: string; enabled: boolean; max_total_cents: number; next_run: number; min_ram_gb: number; fallback_after?: number; fallback_min_ram_gb?: number; held_contacts: number; replies: { status: string; due_at: number; conversation_url: string }[]; latest_run: { status: string; finished_at: number; result: { matches: Lead[]; sources?: { platform: string; status: string; checked: number; reason?: string }[]; listings_checked: number; agent?: { status: string; offer_cents: number; conversation_url?: string } } | null } | null };
type Task = { id: string; title: string; goal?: string; status?: string };
type Job = { id: string; task_id: string; status: string; completed_steps: number; total_steps: number; kind: string; results: { text?: string; ok?: boolean; reason?: string }[] };
const money = (cents: number) => new Intl.NumberFormat('nl-NL', { style: 'currency', currency: 'EUR' }).format(cents/100);
const date = (stamp: number) => new Date(stamp*1000).toLocaleString('nl-NL', { timeZone: 'Europe/Amsterdam', dateStyle: 'medium', timeStyle: 'short' });
async function fetchState(resource: string, signal: AbortSignal) { const r = await fetch(`/api/leon?resource=${resource}`, { signal, cache: 'no-store' }); const d = await r.json() as { error?:string; watches?:Watch[]; jobs?:Job[]; tasks?:Task[] }; if (!r.ok) throw new Error(d.error || 'Werk is niet bereikbaar'); return d; }
function Dots({ names, current, complete = false }: { names: string[]; current: number; complete?: boolean }) { return <ol className="agent-dots" aria-label="Voortgang">{names.map((name,i)=><li key={name} data-state={i<current || complete ? 'done' : i===current ? 'current' : 'next'} aria-current={i===current && !complete ? 'step' : undefined}><span className="agent-dot"/><span>{name}</span></li>)}</ol>; }

export default function ConnectedWork({ onOpenChat }: { demo?: ReactNode; onOpenChat?: () => void }) {
  const [watches,setWatches] = useState<Watch[]>([]); const [jobs,setJobs] = useState<Job[]>([]); const [tasks,setTasks] = useState<Task[]>([]);
  const [agent,setAgent] = useState('all'); const [filter,setFilter] = useState('active'); const [layout,setLayout] = useState('compact'); const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
  const refresh = useCallback(async(signal: AbortSignal)=>{setBusy(true);const results=await Promise.allSettled(['shopper-state','jobs','work-status'].map(r=>fetchState(r,signal)));if(signal.aborted)return;let failed=false;for(const [i,r] of results.entries()){if(r.status==='rejected'){failed=true;continue;}if(i===0)setWatches(r.value.watches || []);if(i===1)setJobs(r.value.jobs || []);if(i===2)setTasks(r.value.tasks || []);}setError(failed?'Een deel van de voortgang is tijdelijk niet bereikbaar.':'');setBusy(false);},[]);
  useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{await refresh(c.signal);if(!c.signal.aborted)timer=setTimeout(poll,15000);};void poll();return()=>{c.abort();clearTimeout(timer);};},[refresh]);
  const visibleWatches = watches.filter(w=>agent!=='tasks' && (filter!=='active'||w.enabled) && (filter!=='paused'||!w.enabled||w.held_contacts>0) && filter!=='done');
  const realTasks = tasks.filter(t=>t.title!=='Chat conversation');
  const visibleTasks = realTasks.filter(t=>agent!=='shopper' && (filter!=='active'||!['done','cancelled'].includes(t.status||'')) && (filter!=='done'||t.status==='done') && (filter!=='paused'||jobs.some(j=>j.task_id===t.id&&j.status==='paused')));
  return <div className="space-view agent-work" data-layout={layout}>
    <header className="agent-page-header"><div><span className="agent-eyebrow">Jouw opdrachten</span><h1>Werk.</h1><p>Geef Leon opdrachten in de chat. Hier zie je hoe ze lopen.</p></div><button className="agent-primary" onClick={onOpenChat}><MessageCircle size={16}/> Geef een opdracht</button></header>
    <div className="agent-filters"><label>Agent<select value={agent} onChange={e=>setAgent(e.target.value)}><option value="all">Alle agents</option><option value="shopper">Shopper</option><option value="tasks">Overige opdrachten</option></select></label><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Actief</option><option value="all">Alles</option><option value="paused">Gepauzeerd</option><option value="done">Afgerond</option></select></label><label>Weergave<select value={layout} onChange={e=>setLayout(e.target.value)}><option value="compact">Compact</option><option value="roomy">Ruim</option></select></label><button className="agent-quiet" disabled={busy} onClick={()=>void refresh(new AbortController().signal)} aria-label="Voortgang verversen"><RefreshCw size={16}/></button></div>
    {error&&<p role="alert" className="agent-error">{error}</p>}
    <div className="agent-task-list">{visibleWatches.map(w=>{const result=w.latest_run?.result;const leads=result?.matches||[];const ready=w.replies?.some(r=>r.status==='ready_for_owner');const stage=ready?4:result?.agent?.status==='confirmed'?3:leads.length?2:w.latest_run?1:0;return <details className="agent-task-card" key={w.id}>
      <summary><div className="agent-task-icon"><ShoppingBag size={19}/></div><div className="agent-task-title"><small>Shopper · {w.platform==='both'?'Marktplaats + Vinted':w.platform}</small><h2>{w.query}</h2><p>{!w.enabled?'Gepauzeerd':ready?'Aanbod klaar voor jou':w.latest_run?.status==='running'?'Aanbiedingen zoeken…':leads.length?`${leads.length} passende leads`:'Verder zoeken naar een passende deal'} · maximaal {money(w.max_total_cents)}</p></div><span className="agent-task-badge">{leads.length} leads <ArrowUpRight size={14}/></span></summary>
      <div className="agent-task-body"><Dots names={['Opdracht','Zoeken','Leads','Gesprekken','Aanbod']} current={stage}/>
        <div className="agent-task-facts"><span>{result?.listings_checked??0} advertenties in de laatste ronde</span><span>Volgende ronde: {date(w.next_run)}</span></div>
        {w.fallback_after&&<p className="agent-muted">Tot {date(w.fallback_after)} voorrang voor {w.min_ram_gb} GB; daarna mag {w.fallback_min_ram_gb} GB als reserve meewegen.</p>}
        {!!w.held_contacts&&<p className="agent-muted">{w.held_contacts} reservegesprek op pauze. Leon antwoordt daar niet.</p>}
        {result?.sources?.map(s=><p key={s.platform} className="agent-muted">{s.platform}: {s.status==='complete'?`${s.checked} advertenties bekeken`:s.reason||'Niet bereikbaar'}</p>)}
        {!leads.length&&<p className="agent-empty">Nog geen passende leads. De opdracht blijft doorlopen.</p>}
        <div className="agent-leads">{leads.map(l=><article key={l.url}><small>{l.platform||w.platform}{l.usable_capacity_gb?` · ${l.usable_capacity_gb} GB bruikbaar`:''}</small><a href={l.url} target="_blank" rel="noreferrer">{l.title.split(' Te koop:')[0].slice(0,150)} <ArrowUpRight size={13}/></a><strong>{l.asking_price_cents===null?'Prijs navragen':`${money(l.asking_price_cents)} vraagprijs`}</strong><p>{l.notes.slice(0,2).join(' · ')}</p></article>)}</div>
        {result?.agent?.conversation_url&&<a href={result.agent.conversation_url} target="_blank" rel="noreferrer">Bekijk gesprek · {result.agent.status==='confirmed'?'bericht bevestigd':'bezorging nog niet bevestigd'}</a>}
        {w.replies?.map(r=><p key={r.conversation_url+r.due_at}>{r.status==='pending'?`Reactie gepland voor ${date(r.due_at)}`:r.status==='ready_for_owner'?'Aanbod klaar om zelf te kopen':r.status==='on_hold'?'Reactie op pauze':r.status==='clicked'?'Reactie verzonden, bezorging nog niet bevestigd':r.status==='attempted'||r.status==='unknown'?'Verzendstatus onzeker; geen dubbele reactie':'Gesprek bijgewerkt'}</p>)}
      </div></details>;})}
      {visibleTasks.slice(0,30).map(t=>{const j=jobs.find(j=>j.task_id===t.id);const done=t.status==='done'||j?.status==='succeeded';return <details className="agent-task-card" key={t.id}><summary><div className="agent-task-icon"><MessageCircle size={18}/></div><div className="agent-task-title"><small>{j?.kind==='openai_text'?'Leon · modelopdracht':'Leon · opdracht'}</small><h2>{t.title}</h2><p>{j?.status||t.status||'Opgeslagen'}</p></div><span className="agent-task-badge">{done?'Afgerond':'Volgen'} <ArrowUpRight size={14}/></span></summary><div className="agent-task-body"><Dots names={['Opdracht','In uitvoering','Resultaat']} current={done?2:j?.status==='running'?1:0} complete={done}/>{t.goal&&<p>{t.goal}</p>}{j&&<p className="agent-muted">{j.completed_steps}/{j.total_steps} bevestigde checkpoints</p>}{j?.results?.map((r,i)=><p key={i}>{r.text?.slice(0,1000)||r.reason||(r.ok?'Checkpoint bevestigd':'Checkpoint niet bevestigd')}</p>)}{!j&&<p className="agent-muted">Opdracht opgeslagen; nog geen uitvoering geregistreerd.</p>}</div></details>;})}
    </div>
    {!visibleWatches.length&&!visibleTasks.length&&<p className="agent-empty">Geen opdrachten in deze weergave. Geef Leon een opdracht in de chat of kies een ander filter.</p>}
  </div>;
}
