'use client';
import { useState, type FormEvent } from 'react';

type Status={configured:boolean;state:string;account?:string;school?:string;calendar_connected?:boolean;appointment_count?:number;mfa_kind?:string;confirmation_number?:string};
type SchoolEvent={id:string;summary:string;start:{date_time:string};location:string};
const messages:Record<string,string>={connected:'Je schoolagenda is verbonden. Leon neemt je lessen mee bij het plannen.',school_needed:'Open de aanmelding van je ingestelde school.',session_expired:'De schoolaanmelding is verlopen. Open de aanmelding opnieuw.',password_needed:'Vul je Microsoft-schoolwachtwoord in.',wrong_password:'Microsoft accepteert dit wachtwoord niet. Controleer het en probeer opnieuw.',mfa_needed:'Microsoft vraagt een extra bevestiging. Controleer je Authenticator of schoolaccount.',signing_in:'Aanmelding controleren…',signed_in_unverified:'De schoolpagina is geopend. De agenda-toegang is nog niet bevestigd.',submission_unknown:'De uitkomst is nog onbekend. Controleer de status; Leon verstuurt je wachtwoord niet opnieuw.',browser_unavailable:'De serveraanmelding is tijdelijk niet bereikbaar.',login_needed:'De Magister-aanmelding op de server moet opnieuw worden geopend.'};
export default function MagisterConnect(){
 const [events,setEvents]=useState<SchoolEvent[]|null>(null);const [status,setStatus]=useState<Status|null>(null);const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function refresh(){try{const r=await fetch('/api/leon?resource=magister-status',{cache:'no-store'});if(!r.ok)throw new Error();setStatus(await r.json() as Status);setError('');}catch{setError('Magister-status niet bereikbaar.');}}
 async function agenda(){if(busy)return;setBusy(true);try{const r=await fetch('/api/leon?resource=magister-calendar',{cache:'no-store'});if(!r.ok)throw new Error();const data=await r.json() as {items:SchoolEvent[];truncated:boolean};setEvents(data.items);setError(data.truncated?'Niet alle schoolafspraken konden worden opgehaald.':'');}catch{setEvents(null);setError('Je schoolagenda is niet bereikbaar. Controleer de aanmelding.');}finally{setBusy(false);}}
 const codeMode=status?.state==='mfa_needed'&&status.mfa_kind==='code';
 async function start(){if(busy)return;setBusy(true);try{const r=await fetch('/api/leon?resource=magister-start',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw new Error();setStatus(await r.json() as Status);setError('');}catch{setError('Schoolaanmelding openen is niet bevestigd. Controleer eerst de status.');}finally{setBusy(false);}}
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');const value=password;setPassword('');try{const requestId=globalThis.crypto?.randomUUID?.()??'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16);return (c==='x'?r:(r&3)|8).toString(16);});const r=await fetch('/api/leon?resource=magister-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:requestId,...(codeMode?{code:value}:{password:value})})});if(!r.ok)throw new Error();setStatus(await r.json() as Status);}catch{setError('De uitkomst is onbekend. Controleer eerst de status; Leon verstuurt niets automatisch opnieuw.');}finally{setBusy(false);}}
 return <details className="google-mail-details" onToggle={e=>{if(e.currentTarget.open&&status===null)void refresh();}}><summary>Magister koppelen</summary>
 {status?.configured?<><p>{status.account??status.school}</p><p>{messages[status.state]??'Controleer de schoolaanmelding.'}</p>{status.confirmation_number&&<p>Nummer in je Authenticator: <strong>{status.confirmation_number}</strong></p>}{(['password_needed','wrong_password'].includes(status.state)||codeMode)&&<form onSubmit={submit}><label>{codeMode?'Verificatiecode':'Schoolwachtwoord'}<input type="password" autoComplete={codeMode?'one-time-code':'current-password'} inputMode={codeMode?'numeric':undefined} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy} required maxLength={codeMode?8:512}/></label><p>Alleen voor deze aanmelding op de server; niet opgeslagen in chat of geheugen.</p><button className="agent-primary" disabled={busy||!password}>{busy?'Aanmelden…':codeMode?'Code bevestigen':'School aanmelden'}</button></form>}<button type="button" className="agent-quiet" disabled={busy} onClick={()=>void refresh()}>Status controleren</button></>:<p>{status?'Schoolkoppeling nog niet ingesteld.':'Schoolaanmelding controleren…'}</p>}{error&&<p role="alert">{error}</p>}
 {status?.calendar_connected&&<><button type="button" className="agent-quiet" disabled={busy} onClick={()=>void agenda()}>Schoolagenda deze week bekijken</button>{events&&<ul>{events.slice(0,6).map(e=><li key={e.id}>{new Date(e.start.date_time).toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})} · {e.summary}{e.location?' · '+e.location:''}</li>)}</ul>}{events&&events.length>6&&<p>En nog {events.length-6} schoolafspraken. Vraag in de chat naar je Magister-agenda voor het volledige overzicht.</p>}</>}
 {status?.configured&&['login_needed','browser_unavailable','username_needed','session_expired','school_needed'].includes(status.state)&&<button type="button" className="agent-primary" disabled={busy} onClick={()=>void start()}>{status.state==='username_needed'?'Doorgaan met leerlingnummer':'Schoolaanmelding openen'}</button>}
 </details>;
}
